COUNTRY_CHOICES = [
    ('', '--- Select Country ---'),
    ('dz', 'Algeria'),
    ('ma', 'Morocco'),
    ('tn', 'Tunisia'),
    ('eg', 'Egypt'),
    ('usa', 'United States'),
    ('ca', 'Canada'),
    ('fr', 'France'),
    ('grm', 'Germany'),
    ('it', 'Italy'),
    ('es', 'Spain'),
    ('uk', 'United Kingdom'),
]

ALGERIA_REGIONS = [
    ('', '--- Select Region ---'),
    ('Adrar', 'Adrar'),
    ('Chlef', 'Chlef'),
    ('Laghouat', 'Laghouat'),
    ('Oum El Bouaghi', 'Oum El Bouaghi'),
    ('Batna', 'Batna'),
    ('Bejaia', 'Béjaïa'),
    ('Biskra', 'Biskra'),
    ('Béchar', 'Béchar'),
    ('Blida', 'Blida'),
    ('Bouira', 'Bouira'),
    ('Tamanrasset', 'Tamanrasset'),
    ('Tebessa', 'Tébessa'),
    ('Tlemcen', 'Tlemcen'),
    ('Tiaret', 'Tiaret'),
    ('Tizi Ouzou', 'Tizi Ouzou'),
    ('Algiers', 'Algiers'),
    ('Djelfa', 'Djelfa'),
    ('Jijel', 'Jijel'),
    ('Sétif', 'Sétif'),
    ('Saïda', 'Saïda'),
    ('Skikda', 'Skikda'),
    ('Sidi Bel Abbès', 'Sidi Bel Abbès'),
    ('Annaba', 'Annaba'),
    ('Guelma', 'Guelma'),
    ('Constantine', 'Constantine'),
    ('Médéa', 'Médéa'),
    ('Mostaganem', 'Mostaganem'),
    ('M\'Sila', 'M\'Sila'),
    ('Mascara', 'Mascara'),
    ('Ouargla', 'Ouargla'),
    ('Oran', 'Oran'),
    ('El Bayadh', 'El Bayadh'),
    ('Illizi', 'Illizi'),
    ('Bordj Bou Arréridj', 'Bordj Bou Arréridj'),
    ('Boumerdès', 'Boumerdès'),
    ('El Tarf', 'El Tarf'),
    ('Tindouf', 'Tindouf'),
    ('Tissemsilt', 'Tissemsilt'),
    ('El Oued', 'El Oued'),
    ('Khenchela', 'Khenchela'),
    ('Souk Ahras', 'Souk Ahras'),
    ('Tipaza', 'Tipaza'),
    ('Mila', 'Mila'),
    ('Aïn Defla', 'Aïn Defla'),
    ('Naâma', 'Naâma'),
    ('Aïn Témouchent', 'Aïn Témouchent'),
    ('Ghardaïa', 'Ghardaïa'),
    ('Relizane', 'Relizane'),
    ('Timimoun', 'Timimoun'),
    ('Bordj Badji Mokhtar', 'Bordj Badji Mokhtar'),
    ('Ouled Djellal', 'Ouled Djellal'),
    ('Béni Abbès', 'Béni Abbès'),
    ('In Salah', 'In Salah'),
    ('In Guezzam', 'In Guezzam'),
    ('Touggourt', 'Touggourt'),
    ('Djanet', 'Djanet'),
    ('El M\'Ghair', 'El M\'Ghair'),
    ('El Menia', 'El Menia'),
]


MOROCCO_REGIONS = [
    ('', '--- Select Region ---'),
    ('Tanger Tetouan Al Hoceima', 'Tanger-Tetouan-Al Hoceima'),
    ('L’Oriental', 'L’Oriental'),
    ('Fès-Meknès', 'Fès-Meknès'),
    ('Rabat-Salé-Kénitra', 'Rabat-Salé-Kénitra'),
    ('Béni Mellal-Khénifra', 'Béni Mellal-Khénifra'),
    ('Casablanca-Settat', 'Casablanca-Settat'),
    ('Marrakech-Safi', 'Marrakech-Safi'),
    ('Drâa-Tafilalet', 'Drâa-Tafilalet'),
    ('Souss-Massa', 'Souss-Massa'),
    ('Guelmim-Oued Noun', 'Guelmim-Oued Noun'),
    ('Laâyoune-Sakia El Hamra', 'Laâyoune-Sakia El Hamra'),
    ('Dakhla-Oued Ed Dahab', 'Dakhla-Oued Ed Dahab'),
]

US_STATES = [
    ('', '--- Select State ---'),
    ('Alabama', 'Alabama'),
    ('Alaska', 'Alaska'),
    ('Arizona', 'Arizona'),
    ('Arkansas', 'Arkansas'),
    ('California', 'California'),
    ('Colorado', 'Colorado'),
    ('Connecticut', 'Connecticut'),
    ('Delaware', 'Delaware'),
    ('Florida', 'Florida'),
    ('Georgia', 'Georgia'),
    ('Hawaii', 'Hawaii'),
    ('Idaho', 'Idaho'),
    ('Illinois', 'Illinois'),
    ('Indiana', 'Indiana'),
    ('Iowa', 'Iowa'),
    ('Kansas', 'Kansas'),
    ('Kentucky', 'Kentucky'),
    ('Louisiana', 'Louisiana'),
    ('Maine', 'Maine'),
    ('Maryland', 'Maryland'),
    ('Massachusetts', 'Massachusetts'),
    ('Michigan', 'Michigan'),
    ('Minnesota', 'Minnesota'),
    ('Mississippi', 'Mississippi'),
    ('Missouri', 'Missouri'),
    ('Montana', 'Montana'),
    ('Nebraska', 'Nebraska'),
    ('Nevada', 'Nevada'),
    ('New Hampshire', 'New Hampshire'),
    ('New Jersey', 'New Jersey'),
    ('New Mexico', 'New Mexico'),
    ('New York', 'New York'),
    ('North Carolina', 'North Carolina'),
    ('North Dakota', 'North Dakota'),
    ('Ohio', 'Ohio'),
    ('Oklahoma', 'Oklahoma'),
    ('Oregon', 'Oregon'),
    ('Pennsylvania', 'Pennsylvania'),
    ('Rhode Island', 'Rhode Island'),
    ('South Carolina', 'South Carolina'),
    ('South Dakota', 'South Dakota'),
    ('Tennessee', 'Tennessee'),
    ('Texas', 'Texas'),
    ('Utah', 'Utah'),
    ('Vermont', 'Vermont'),
    ('Virginia', 'Virginia'),
    ('Washington', 'Washington'),
    ('West Virginia', 'West Virginia'),
    ('Wisconsin', 'Wisconsin'),
    ('Wyoming', 'Wyoming'),
]


CANADA_PROVINCES = [
    ('', '--- Select Province ---'),
    ('Alberta', 'Alberta'),
    ('British Columbia', 'British Columbia'),
    ('Manitoba', 'Manitoba'),
    ('New Brunswick', 'New Brunswick'),
    ('Newfoundland and Labrador', 'Newfoundland and Labrador'),
    ('Northwest Territories', 'Northwest Territories'),
    ('Nova Scotia', 'Nova Scotia'),
    ('Nunavut', 'Nunavut'),
    ('Ontario', 'Ontario'),
    ('Prince Edward Island', 'Prince Edward Island'),
    ('Quebec', 'Quebec'),
    ('Saskatchewan', 'Saskatchewan'),
    ('Yukon', 'Yukon'),
]


FRANCE_REGIONS = [
    ('', '--- Select Region ---'),
    ('Auvergne Rhone Alpes', 'Auvergne-Rhône-Alpes'),
    ('Bourgogne Franche', 'Bourgogne-Franche-Comté'),
    ('Bretagne', 'Bretagne'),
    ('Centre Val de Loire', 'Centre-Val de Loire'),
    ('Corse', 'Corse'),
    ('Grand Est', 'Grand Est'),
    ('Hauts', 'Hauts-de-France'),
    ('Ile', 'Île-de-France'),
    ('Normandie', 'Normandie'),
    ('Nouvelle Aquitaine', 'Nouvelle-Aquitaine'),
    ('Occitanie', 'Occitanie'),
    ('Pays de la Loire', 'Pays de la Loire'),
    ('Provence-Alpes-Côte d\'Azur', "Provence-Alpes-Côte d\'Azur"),
]

GERMANY_STATES = [
    ('', '--- Select State ---'),
    ('Baden-Württemberg', 'Baden-Württemberg'),
    ('Bavaria', 'Bavaria'),
    ('Berlin', 'Berlin'),
    ('Brandenburg', 'Brandenburg'),
    ('Bremen', 'Bremen'),
    ('Hamburg', 'Hamburg'),
    ('Hesse', 'Hesse'),
    ('Mecklenburg-Vorpommern', 'Mecklenburg-Vorpommern'),
    ('Lower Saxony', 'Lower Saxony'),
    ('North Rhine-Westphalia', 'North Rhine-Westphalia'),
    ('Rhineland-Palatinate', 'Rhineland-Palatinate'),
    ('Saarland', 'Saarland'),
    ('Saxony', 'Saxony'),
    ('Saxony-Anhalt', 'Saxony-Anhalt'),
    ('Schleswig-Holstein', 'Schleswig-Holstein'),
    ('Thuringia', 'Thuringia'),
]

ITALY_REGIONS = [
    ('', '--- Select Region ---'),
    ('Abruzzo', 'Abruzzo'),
    ('Basilicata', 'Basilicata'),
    ('Calabria', 'Calabria'),
    ('Campania', 'Campania'),
    ('Emilia-Romagna', 'Emilia-Romagna'),
    ('Friuli Venezia Giulia', 'Friuli Venezia Giulia'),
    ('Lazio', 'Lazio'),
    ('Liguria', 'Liguria'),
    ('Lombardia', 'Lombardia'),
    ('Marche', 'Marche'),
    ('Molise', 'Molise'),
    ('Piemonte', 'Piemonte'),
    ('Puglia', 'Puglia'),
    ('Sardegna', 'Sardegna'),
    ('Sicilia', 'Sicilia'),
    ('Toscana', 'Toscana'),
    ('Trentino-Alto Adige', 'Trentino-Alto Adige'),
    ('Umbria', 'Umbria'),
    ('Valle d’Aosta', 'Valle d’Aosta'),
    ('Veneto', 'Veneto'),
]

EGYPT_REGIONS = [
    ('', '--- Select Region ---'),
    ('Cairo', 'Cairo'),
    ('Alexandria', 'Alexandria'),
    ('Giza', 'Giza'),
    ('Port Said', 'Port Said'),
    ('Suez', 'Suez'),
    ('Aswan', 'Aswan'),
    ('Luxor', 'Luxor'),
    ('Assiut', 'Assiut'),
    ('Ismailia', 'Ismailia'),
]

TUNISIA_REGIONS = [
    ('', '--- Select Region ---'),
    ('Tunis', 'Tunis'),
    ('Ariana', 'Ariana'),
    ('Ben Arous', 'Ben Arous'),
    ('Manouba', 'Manouba'),
    ('Nabeul', 'Nabeul'),
    ('Zaghouan', 'Zaghouan'),
    ('Bizerte', 'Bizerte'),
    ('Béja', 'Béja'),
    ('Jendouba', 'Jendouba'),
    ('Le Kef', 'Le Kef'),
    ('Siliana', 'Siliana'),
    ('Kairouan', 'Kairouan'),
    ('Kasserine', 'Kasserine'),
    ('Sidi Bouzid', 'Sidi Bouzid'),
    ('Sousse', 'Sousse'),
    ('Monastir', 'Monastir'),
    ('Mahdia', 'Mahdia'),
    ('Sfax', 'Sfax'),
    ('Gafsa', 'Gafsa'),
    ('Tozeur', 'Tozeur'),
    ('Kebili', 'Kebili'),
    ('Gabès', 'Gabès'),
    ('Medenine', 'Medenine'),
    ('Tataouine', 'Tataouine'),
]

SPAIN_REGIONS = [
    ('', '--- Select Region ---'),
    ('Andalusia', 'Andalusia'),
    ('Aragon', 'Aragon'),
    ('Asturias', 'Asturias'),
    ('Balearic Islands', 'Balearic Islands'),
    ('Basque Country', 'Basque Country'),
    ('Canary Islands', 'Canary Islands'),
    ('Cantabria', 'Cantabria'),
    ('Castile and León', 'Castile and León'),
    ('Castilla-La Mancha', 'Castilla-La Mancha'),
    ('Catalonia', 'Catalonia'),
    ('Extremadura', 'Extremadura'),
    ('Galicia', 'Galicia'),
    ('Madrid', 'Madrid'),
    ('Murcia', 'Murcia'),
    ('Navarre', 'Navarre'),
    ('La Rioja', 'La Rioja'),
    ('Valencian Community', 'Valencian Community'),
]

UK_REGIONS = [
    ('', '--- Select Country ---'),
    ('ENG', 'England'),
    ('SCT', 'Scotland'),
    ('WLS', 'Wales'),
    ('NIR', 'Northern Ireland'),
]

COUNTRY_REGION_CHOICES = {
    'dz': ALGERIA_REGIONS,
    'ma': MOROCCO_REGIONS,
    'tn': TUNISIA_REGIONS,
    'eg': EGYPT_REGIONS,
    'usa': US_STATES,
    'ca': CANADA_PROVINCES,
    'fr': FRANCE_REGIONS,
    'grm': GERMANY_STATES,
    'it': ITALY_REGIONS,
    'es': SPAIN_REGIONS,
    'uk': UK_REGIONS,
}

GENDER_CHOICES = [
    ('male', 'Male'),
    ('female', 'Female'),
]

Departments = [
    ('Cardiologist','Cardiologist'),
    ('Dermatologists','Dermatologists'),
    ('Emergency Medicine Specialists','Emergency Medicine Specialists'),
    ('Allergists/Immunologists','Allergists/Immunologists'),
    ('Anesthesiologists','Anesthesiologists'),
    ('Colon and Rectal Surgeons','Colon and Rectal Surgeons'),
    ('Generalist','Generalist'),
]

BLOOD_GROUP_CHOICES = [
        ('A+', 'A+'),
        ('A-', 'A-'),
        ('B+', 'B+'),
        ('B-', 'B-'),
        ('AB+', 'AB+'),
        ('AB-', 'AB-'),
        ('O+', 'O+'),
        ('O-', 'O-'),
]