# Generated by Django 5.2 on 2025-05-24 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=7)),
                ('country', models.CharField(choices=[('', '--- Select Country ---'), ('dz', 'Algeria'), ('ma', 'Morocco'), ('tn', 'Tunisia'), ('eg', 'Egypt'), ('usa', 'United States'), ('ca', 'Canada'), ('fr', 'France'), ('grm', 'Germany'), ('it', 'Italy'), ('es', 'Spain'), ('uk', 'United Kingdom')], max_length=10)),
                ('region', models.CharField(blank=True, default='', max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administrators',
                'db_table': 'administrator',
            },
        ),
        migrations.CreateModel(
            name='AdministratorEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='hospital.administrator')),
            ],
            options={
                'db_table': 'administrator_email',
                'unique_together': {('administrator', 'email')},
            },
        ),
        migrations.CreateModel(
            name='AdministratorPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='hospital.administrator')),
            ],
            options={
                'db_table': 'administrator_phone',
                'unique_together': {('administrator', 'phone')},
            },
        ),
    ]
