# Generated by Django 5.2 on 2025-05-25 14:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_administrator_administratoremail_administratorphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=7)),
                ('department', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons'), ('Generalist', 'Generalist')], default='Cardiologist', max_length=40)),
                ('speciality', models.CharField(default='', max_length=30)),
                ('country', models.CharField(choices=[('', '--- Select Country ---'), ('dz', 'Algeria'), ('ma', 'Morocco'), ('tn', 'Tunisia'), ('eg', 'Egypt'), ('usa', 'United States'), ('ca', 'Canada'), ('fr', 'France'), ('grm', 'Germany'), ('it', 'Italy'), ('es', 'Spain'), ('uk', 'United Kingdom')], max_length=10)),
                ('region', models.CharField(blank=True, default='', max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('license_number', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Brand Name')),
                ('inn', models.CharField(max_length=100, verbose_name='International Nonproprietary Name')),
                ('form', models.CharField(choices=[('COMP', 'Tablet'), ('GEL', 'Capsule'), ('SIROP', 'Syrup'), ('POM', 'Ointment')], max_length=50)),
                ('dosage', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Medication',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=7)),
                ('department', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons'), ('Generalist', 'Generalist')], default='Cardiologist', max_length=50)),
                ('speciality', models.CharField(default='', max_length=50)),
                ('country', models.CharField(choices=[('', '--- Select Country ---'), ('dz', 'Algeria'), ('ma', 'Morocco'), ('tn', 'Tunisia'), ('eg', 'Egypt'), ('usa', 'United States'), ('ca', 'Canada'), ('fr', 'France'), ('grm', 'Germany'), ('it', 'Italy'), ('es', 'Spain'), ('uk', 'United Kingdom')], max_length=10)),
                ('region', models.CharField(blank=True, default='', max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nurse',
                'verbose_name_plural': 'Nurses',
                'db_table': 'nurse',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=7)),
                ('country', models.CharField(choices=[('', '--- Select Country ---'), ('dz', 'Algeria'), ('ma', 'Morocco'), ('tn', 'Tunisia'), ('eg', 'Egypt'), ('usa', 'United States'), ('ca', 'Canada'), ('fr', 'France'), ('grm', 'Germany'), ('it', 'Italy'), ('es', 'Spain'), ('uk', 'United Kingdom')], max_length=10)),
                ('region', models.CharField(blank=True, default='', max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('code_postal', models.IntegerField(blank=True)),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('age', models.IntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('symptoms', models.TextField(default=None, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('duree_validite', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Validité (mois)')),
                ('notes', models.TextField(blank=True, verbose_name='Instructions spéciales')),
                ('archivee', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(limit_choices_to={'groups__name': 'Doctors'}, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='hospital.patient')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'ordering': ['-date'],
                'permissions': [('print_ordonnance', 'Peut imprimer une ordonnance')],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posologie', models.CharField(max_length=200, verbose_name="Mode d'emploi")),
                ('duree_jours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Duree (jours)')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité prescrite')),
                ('renouvelable', models.BooleanField(default=False, verbose_name='Renouvelable ?')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.medication')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospital.ordonnance')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
            },
        ),
        migrations.CreateModel(
            name='DoctorEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='hospital.doctor')),
            ],
            options={
                'db_table': 'doctor_email',
                'unique_together': {('doctor', 'email')},
            },
        ),
        migrations.CreateModel(
            name='DoctorPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='hospital.doctor')),
            ],
            options={
                'db_table': 'doctor_phone',
                'unique_together': {('doctor', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='NurseEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='hospital.nurse')),
            ],
            options={
                'db_table': 'nurse_email',
                'unique_together': {('nurse', 'email')},
            },
        ),
        migrations.CreateModel(
            name='NursePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='hospital.nurse')),
            ],
            options={
                'db_table': 'nurse_phone',
                'unique_together': {('nurse', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='PatientEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='hospital.patient')),
            ],
            options={
                'db_table': 'patient_email',
                'unique_together': {('patient', 'email')},
            },
        ),
        migrations.CreateModel(
            name='PatientPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='hospital.patient')),
            ],
            options={
                'db_table': 'patient_phone',
                'unique_together': {('patient', 'phone')},
            },
        ),
    ]
